nsis integration
git-svn-id: svn://svn.debian.org/svn/tux4kids/tuxmath/trunk@44 47d30e19-490b-0410-9d18-e851f4e465b3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -861,6 +861,9 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-sdl-prefix=PFX   Prefix where SDL is installed (optional)
   --with-sdl-exec-prefix=PFX Exec prefix where SDL is installed (optional)
+  --with-dll-directory=path
+                          set the path where dll for TuxMath are
+                          $(NSI_DLL_DIR)
 
 Some influential environment variables:
   CC          C compiler command
@@ -1698,7 +1701,7 @@ fi
 
 
 # Define the identity of the package.
- PACKAGE=TuxMath
+ PACKAGE=tuxmath
  VERSION=0.96
 
 
@@ -4854,13 +4857,124 @@ _ACEOF
    LIBS="$LIBS -lgw32c -luuid -lole32 -lwsock32 -mwindows"
    CPPFLAGS="$CPPFLAGS -idirafter $prefix/include/glibc"
    #CPPFLAGS="$CPPFLAGS -I$prefix/include/glibc"
+   # Extract the first word of ""$target_alias-windres"", so it can be a program name with args.
+set dummy "$target_alias-windres"; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_WINDRES+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $WINDRES in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_WINDRES="$WINDRES" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_WINDRES="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_WINDRES" && ac_cv_path_WINDRES="no"
+  ;;
+esac
+fi
+WINDRES=$ac_cv_path_WINDRES
+
+if test -n "$WINDRES"; then
+  echo "$as_me:$LINENO: result: $WINDRES" >&5
+echo "${ECHO_T}$WINDRES" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 fi
 
 
 
+NSI_INSTALL_DIR=mingw32
+NSI_DLL_DIR=~/tuxmath_dll
+
+
+# Check whether --with-dll-directory or --without-dll-directory was given.
+if test "${with_dll_directory+set}" = set; then
+  withval="$with_dll_directory"
+  dll_path=$withval
+else
+  dll_path=no
+fi;
+
+
+
+if test "$dll_path" = no; then
+  NSI_BUILD_TRUE=
+  NSI_BUILD_FALSE='#'
+else
+  NSI_BUILD_TRUE='#'
+  NSI_BUILD_FALSE=
+fi
+
+
+
+
+
+if test $dll_path != no; then
+NSI_DLL_DIR=$dll_path
+fi
+
+# Extract the first word of "makensis", so it can be a program name with args.
+set dummy makensis; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_NSIS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $NSIS in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_NSIS="$NSIS" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_NSIS="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_NSIS" && ac_cv_path_NSIS="no"
+  ;;
+esac
+fi
+NSIS=$ac_cv_path_NSIS
+
+if test -n "$NSIS"; then
+  echo "$as_me:$LINENO: result: $NSIS" >&5
+echo "${ECHO_T}$NSIS" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
 #AC_CONFIG_FILES([Makefile])
 
-                    ac_config_files="$ac_config_files Makefile src/Makefile"
+                              ac_config_files="$ac_config_files Makefile src/Makefile nsis/tuxmath.nsi"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -4977,6 +5091,13 @@ if test -z "${BUILD_MINGW32_TRUE}" && test -z "${BUILD_MINGW32_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_MINGW32\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_MINGW32\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${NSI_BUILD_TRUE}" && test -z "${NSI_BUILD_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NSI_BUILD\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NSI_BUILD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -5426,6 +5547,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
+  "nsis/tuxmath.nsi" ) CONFIG_FILES="$CONFIG_FILES nsis/tuxmath.nsi" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -5576,7 +5698,13 @@ s,@POW_LIB@,$POW_LIB,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@BUILD_MINGW32_TRUE@,$BUILD_MINGW32_TRUE,;t t
 s,@BUILD_MINGW32_FALSE@,$BUILD_MINGW32_FALSE,;t t
+s,@WINDRES@,$WINDRES,;t t
 s,@PACKAGE_DATA_DIR@,$PACKAGE_DATA_DIR,;t t
+s,@NSI_BUILD_TRUE@,$NSI_BUILD_TRUE,;t t
+s,@NSI_BUILD_FALSE@,$NSI_BUILD_FALSE,;t t
+s,@NSI_INSTALL_DIR@,$NSI_INSTALL_DIR,;t t
+s,@NSI_DLL_DIR@,$NSI_DLL_DIR,;t t
+s,@NSIS@,$NSIS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
